2024-03-25 16:24:41,531 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2024-03-25 16:24:41,531 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\instabot\bot\bot.py
2024-03-25 16:24:41,533 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2024-03-25 16:24:42,206 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2024-03-25 16:24:42,206 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2024-03-25 16:24:42,207 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2024-03-25 16:24:42,207 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
